### ISSUE TITLE
Some experiments with your code and a reading of your current report

### ISSUE THREAD

**Issue by ylb76** [WillianPaiva/dominion_datamining#2]
I put everything in the following file.

 It would be nice if all member could indicate here that they where able to read these comments. 

[comments.txt](https://github.com/WillianPaiva/dominion_datamining/files/129932/comments.txt)

[partial_data.csv.txt](https://github.com/WillianPaiva/dominion_datamining/files/129935/partial_data.csv.txt)
[1000games_win_los_points.pdf](https://github.com/WillianPaiva/dominion_datamining/files/129936/1000games_win_los_points.pdf)
[untruncated_win_lose_points.pdf](https://github.com/WillianPaiva/dominion_datamining/files/129937/untruncated_win_lose_points.pdf)

[pymong.py.txt](https://github.com/WillianPaiva/dominion_datamining/files/129938/pymong.py.txt)

**Comment by WillianPaiva** [comment]
about the problem with directories being paritally read i really dont have this proble like on the depo we have a total of 413416 files once the program is finished i have the same amount on the mongodb.

please check that you have only bz2 files on the "sampleLogs" folder.

about the problem with the "_id" field that is not happening on my side if you could provide the stack trace of the problem i cam have a look on it 

and a sample that plots the first 5 players elo curve is already on the depo. 

also provided the bugs i fixed this weekend i recommend deleting all the folders of mongo and restart the process of parssing 

as the elo calculation had a bug and was double inserting the game on the database

**Comment by ebayol** [comment]
as asked, i can read these comments. I don't understand what the axis values in the pdf files mean, are they victory points or something else?

**Comment by ylb76** [comment]
Yes, vertical axis corresponds to loser's victory points and horizontal axis to winner's victory points.

**Comment by ylb76** [comment]
I have only bz2 files in sampleLogs folder.

**Comment by ylb76** [comment]
Here the end of  trace of the problem while running run.sh and the mongo run showing only 209 parsed games.
[error4.txt](https://github.com/WillianPaiva/dominion_datamining/files/131104/error4.txt)

**Comment by lilianamllf** [comment]
Par rapport à « bot detection », je pense il y a des autres donnes à tenir en compte, en plus de la date de début du jeu. Par exemple le nombre de parties qu’un même joueur en x temps. Si le nombre de parties est égal ou supérieur à y nombre, on pourrait détecter que il y a la possibilité de que il s’agie  de un bot.
Par ailler je n’ai pas compris l’analyse des deux premières mains. C’est les deux premiers jeux, ou les deux premiers tours?. Et « générer » cela veut dire quoi ? Les achats plus les coins obtenus avec les cartes d’actions ?   

ylb> J ai fait un peu de python sur les logs pour reperer le vainqueur et le perdant puis generer sous forme de tableau la distribution des cartes dans les decks dans un fichier csv.
Ensuite, j affiche des points corresponds au couple (points de victoire du vainqueur, points de victoire du perdant)

**Comment by ktagnaouti** [comment]
oui je suis là,j'essaye de comprendre les fichiers que vous avez mis et les prendre en considération.

**Comment by WillianPaiva** [comment]
ok i found out the problem with not all logs being parsed what happens it some files one the others logs that havent being tested yet has dome "user names with keywords" im working on improving this to be able to skip the logs with the bad user names and keep going without stop havent done anything like this before because is easy to debug if the program just stops on the problematic log 

about the _id problem  that didn`t happen om my side but i found the possible problem and pushed the fix 

edit:

the parser is done to run on a clean database so if you gonna run another time just delete all mongo folders

**Comment by WillianPaiva** [comment]
note if you get som exceptions on the parsing part of the program try to lower the number of threads at the moment is using five but if i use over 9 it gets some problems .

to lower the threads is in the main :

```
         test.runParser(5);
```

**Comment by WillianPaiva** [comment]
i was reading your python code and just to have an clarification 

```
dict_logs = []
for a_log in logs.find({"players":{"$size":2},"winners":{"$size":1}}):
    dict_logs += [a_log]
    if len(dict_logs) % 10000 == 0:
        print(len(dict_logs))
```

when you copy all the logs to the dict_logs it can take a lot of memory depending on the querry.
on java the mongo drive has an object called FindIterable that returns the documents on bachs of files to not over populate the memory .
i didn`t really had time to look up the python drive but maybe theris the same kind of manipulation on python.

**Comment by ylb76** [comment]
Thanks for the remark about python. I will have a look. (in practice it tooks may be no more than one
minute to visit these logs so I did not try to optimize.
